[project]
name = "pishro-lib"
version = "0.1.0"
description = "Pishro is a package manager and deployment tool for docker swarm"
readme = "README.md"
authors = [
    { name = "Siavash Outadi", email = "siavash.outadi@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
pishro-lib = "pishro_lib:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
